version: "3"
services:
  jellyfin:
    image: linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./jellyfin_config:/config
      - /data/mediaserver/media/tvshows:/data/tvshows
      - /data/mediaserver/media/movies:/data/movies
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8096:8096
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./sonarr_config:/config
      - /data/mediaserver:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./radarr_config:/config
      - /data/mediaserver:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./bazarr_config:/config
      - /data/mediaserver/media:/data/media
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6767:6767
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:develop
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
    ports:
      - 5055:5055
    volumes:
      - ./jellyseerr_config:/app/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr