version: "3"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM=claim-pb4U4ctxaDAAxpJH4w4u
    volumes:
      - ./plex_config:/config
      - /data/media/tvshows:/tv
      - /data/media/movies:/movies
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 32400:32400
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./sonarr_config:/config
      - /data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./radarr_config:/config
      - /data:/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./bazarr_config:/config
      - /data/media:/data/media
    ports:
      - 6767:6767
    restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./overseerr_config:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5055:5055
    restart: unless-stopped
    depends_on:
      - radarr
      - sonarr